package config

type ActionsConfig struct {}
type APIPlatformConfig struct {}
type APIGatewayConfig struct {}
type APIGeeConfig struct {}
type AppEngineConfig struct {}
type AutoscalerConfig struct {}
type BigqueryConfig struct {}
type BigqueryBiEngineConfig struct {}
type BigqueryDataTransferConfig struct {}
type BigtableConfig struct {}
type CloudFunctions struct {}
type CloudIOTConfig struct {}
type CloudSQLConfig struct {}
type CloudTasksConfig struct {}
type CloudTraceConfig struct {}
type ComposerConfig struct {}
type ComputeConfig struct {}
type ContactCenterInsightsConfig struct {}
type ContainerConfig struct {}
type DataflowConfig struct {}
type DataprocConfig struct {}
type DatastoreConfig struct {}
type DatastreamConfig struct {}
type DLPConfig struct {}
type DNSConfig struct {}
type FileConfig struct {}
type FirebaseAppCheckConfig struct {}
type FirebaseDatabaseConfig struct {}
type FirestoreConfig struct {}
type FirewallInsightsConfig struct {}
type HealthcareConfig struct {}
type IAMConfig struct {}
type IDSConfig struct {}
type InterconnectConfig struct {}
type LoadbalancingConfig struct {}
type LoggingConfig struct {}
type ManagedIdentitiesConfig struct {}
type MemcacheConfig struct {}
type MetastoreConfig struct {}
type MLConfig struct {}
type MonitoringConfig struct {}
type NetworkingConfig struct {}
type NetworkSecurityConfig struct {}
type OSConfigConfig struct {}
type PrivateECAConfig struct {}
type PubsubConfig struct {}
type PubsubLiteConfig struct {}
type RecaptchaEnterpriseConfig struct {}
type RecommendationEngineConfig struct {}
type RedisConfig struct {}
type RouterConfig struct {}
type RunConfig struct {}
type ServiceRuntimeConfig struct {}
type SpannerConfig struct {}
type StorageConfig struct {}
type StorageTransferConfig struct {}
type TPUConfig struct {}
type VPCAccessConfig struct {}
type VPNConfig struct {}
type WorkflowsConfig struct {}